src/components/property/Property.jsx
I have created the property listing first page with route "/property"
=> property lisitng first page

src/components/blog/Blog.jsx, src/components/blog/BlogView.jsx, src/components/property/Flow2-1/Flow2b.jsx
blog cards and the blogview is fixed according to the figma, also fix the gap and iframe in the property show more option.
=> changes for blog according to figma and fix the propert show more.

src/components/footer/Footer.jsx, src/components/navbar/NavBar.jsx
=> updated navbar and footer

src/components/Layout.jsx, src/components/index.js, src/components/landlord/LandlordPage.jsx
=> Added Landlord Page

src/components/property/Flow2-1/Flow2a1.jsx
Changed arrow scroll feature implemented on opening card image.
=> Changed arrow scroll feature implemented on opening card image.

src/components/contact/Contact.jsx, src/components/landingpage/home/getintouch.jsx
In this pull request, I have made the following changes to improve the efficiency and functionality of the contact form:
**Fixing Empty Form Submission:** Previously, the contact form was not properly handling empty form submissions. This issue has been addressed by adding validation checks to ensure that all required fields are filled before submitting the form.
**Adding Try-Catch Block in Contact Form:** To handle any potential errors that may occur during the form submission process, I have added a try-catch block around the code that sends the contact form data to the server. This ensures that any errors are caught and handled gracefully, preventing the form from crashing.
**Loader UI for Sending Button:** To enhance the user experience, I have implemented a loader UI for the sending …
=> Fixing Empty Form Submission and Adding Try-Catch Block in Contact Form

src/components/About/AboutUs.jsx, src/components/About/faq.jsx, src/components/blog/Blog.jsx, src/components/contact/Contact.jsx, src/components/landingpage/home/about.jsx, src/components/landingpage/home/getintouch.jsx, src/components/navbar/NavBar.jsx, src/components/property/Flow2-1/Flow2a1.jsx, src/components/property/Flow2-1/Flow2b.jsx, src/components/property/Listing.jsx, src/components/property/Property.jsx, src/components/reviews/Reviews.jsx, src/components/service/Service.jsx
- Improved Layout Consistency. Aligned Header, Footer, and Main content.
- Review Button Toggle Corrected on the Individual Listing Page.
=> Layout Correction and Reviews Button Toggle

package-lock.json, package.json, src/components/property/listingComponents/Cards.jsx
=> Training : Copy Link Feature added

src/components/About/styles/card.css, src/components/service/Card.jsx, src/components/service/Service.jsx
=> services responsiveness and about logo

src/components/About/AboutUs.jsx, src/components/dashboard/Account-Security.jsx, src/components/dashboard/Sidebar.jsx
=> Account-Security Component added

src/components/Hiringpartner/HiringPartners.css, src/components/Landing.jsx, src/components/landingpage/home/about.jsx
Update Hiring Partner component
=> update Hiring partner

package-lock.json, package.json, src/components/Layout.jsx, src/components/landlord/LandlordDashboardProfileForm.jsx, src/components/navbar/NavBar.jsx
>email id is now not changable
>you can upload your profile photo and you able to see that in navbar
=> updated profile page and profile photo can be added

package-lock.json, package.json, src/components/Landing.jsx, src/components/OurReach/OurReach.jsx
<Mriganka Das>
<dasmriganka.2002@gmail.com>
=> chore: OurReach feature is addd

src/components/Hiringpartner/HiringPartners.jsx
Updated Social links in hiring partner component
=> updated hiring partner

src/components/landlord/LandlordDashboardProfileForm.jsx, src/components/property/Flow2-1/Flow2a1.jsx, src/components/property/Flow2-1/Flow2b.jsx, src/components/property/Flow2-1/Location.jsx, src/components/property/Listing.jsx, src/components/reviews/Reviews.jsx, src/config/config.js, src/constant/constant.js
=> Merger Training with Development

src/components/landlord/LandlordDashboardMyProperties.jsx, src/components/property/Flow2-1/Flow2a1.jsx, src/components/property/compare-prop/CompareProperty.jsx, src/components/property/listingComponents/Cards.jsx
Copy feature added in compare property and My property.
=> Copy Feature

src/components/Hiringpartner/HiringPartners.jsx
updated hiring partner component
=> adjusted component to center

src/components/landlord/LandlordDashboardAccountSecurity.jsx
Changes 
> LandlordDashboardAccountSecurity.jsx
by Taman Hansaliya
=> Make LandlordDashboardAccountSecurity component fully responsive

src/components/OurReach/OurReach.jsx, src/components/property/Listing.jsx, src/components/property/listingComponents/Cards.jsx
=>  chore: Responsive updated

src/components/landingpage/home/PropertyCarousel.jsx, src/components/navbar/NavBar.jsx
Code shorting in Navbar.jsx
file path :
src\components\navbar\NavBar.jsx
no error found
=> Code shorting NavBar

package-lock.json, src/components/landingPageComp/testimonial.jsx
Applied Tailwind's hidden class to hide the testimonials section temporarily.
=> temporarily hide testimonials

src/pages/blog/components/card/BlogItem.jsx, src/pages/blog/components/card/BlogList.jsx
Changes done in blog/components/card/BlogItem.jsx and 
blog/components/card/BlogList.jsx
=> Made the blog page responsive

src/pages/Dashboard/landlord/LandlordDashboardMyProperties.jsx
adds a "Delete" button to the MyProperty card component. The new functionality allows users to delete a specific property from their list. The implementation includes:
A delete button within each property card.
A handler function that sends a DELETE request to the backend API to remove the property.
UI updates that remove the deleted property from the UI without requiring a full page reload.
=> Add Delete Button to MyProperty Card Component

src/pages/blog/BlogView.jsx, src/pages/blog/components/card/Likes.jsx
=> blog likes issue fixed

src/components/landingPageComp/Institution.jsx, src/components/landingPageComp/OurReach.jsx
Updated the ourReach.jsx and institution.jsx components to support responsive design, optimizing their layout and styling for better performance and usability across various screen resolutions and devices.
=> Make ourReach.jsx and institution.jsx components responsive

src/components/landingPageComp/HiringPartners.jsx
Implemented a responsive slider for the "Our Hiring Partners" section, ensuring it adapts well to different screen sizes.
Added a marquee animation to create a continuous sliding effect for partner logos.
Integrated a clickable functionality on each logo to navigate to the corresponding URL using handleLogoClick.
Designed with Tailwind CSS for consistent spacing, typography, and responsiveness.
Included flex and gap utilities for proper alignment of logos across devices.
Ensured overflow handling for smooth animation within the container.
=> Add responsive slider for 'Our Hiring Partners' section with clickable logos and marquee animation.

src/components/AboutComp/About_Card.jsx, src/components/AboutComp/Faq.jsx, src/components/AboutComp/styles/card.css, src/pages/About/AboutUs.jsx, src/pages/About/about.css
Add responsive improvements to About Us animation for better adaptability across screen sizes
=> About Us animation part responsive

src/pages/property/Listing.jsx, src/pages/property/compare-prop/CompareProperty.jsx
Added the submit button with forms to send the data to the backend for sending the mail
=> Submit button Added

src/components/landingPageComp/ChatApp.jsx
pull some changes.
Made proper responsive. 
Removed the purple border.
Added the fetch response correctly.
Edited the asset image extension correctly.
=> Changes in previous PR

src/components/index.js, src/components/landingPageComp/homepageComp/BottomBg.jsx, src/components/landingPageComp/homepageComp/HomeDown.jsx, src/components/landingPageComp/homepageComp/style/background.css, src/pages/Service.jsx, src/pages/property/Listing.jsx
=> Animation of Mobile View Corrected

src/components/landingPageComp/homepageComp/style/background.css
=> HomePage animation

src/components/landingPageComp/homepageComp/BottomBg.jsx, src/components/landingPageComp/homepageComp/style/background.css, src/pages/Dashboard/landlord/LandlordDashboard.jsx, src/pages/Dashboard/landlord/LandlordDashboardAccountSecurity.jsx, src/pages/Dashboard/landlord/LandlordDashboardAddProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardMyFavourites.jsx, src/pages/Dashboard/landlord/LandlordDashboardMyProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardProfileForm.jsx, src/pages/Dashboard/landlord/LandlordDashboardSidebar.jsx, src/pages/Dashboard/landlord/LandlordDashboardWelcomePage.jsx
=> Dashboard Responsive Done

src/pages/blog/components/LatestTrending.jsx, tailwind.config.js
in the blog section, the button design of the latest and trending now matches the Figma
=> Updated button design in blog section

src/components/Footer.jsx, src/components/landingPageComp/About.jsx, src/components/landingPageComp/HiringPartners.jsx, src/components/landingPageComp/Institution.jsx, src/components/landingPageComp/OurReach.jsx, src/components/navbar/NavBar.jsx, src/index.css, src/pages/Service.jsx
"Services" text 
Footer spacing
Navbar as per old figma , non cut top pages part
our reach mobile view
hiring partner no animation
Institution pause, infinite animation
=> Minor Changes as per pdf

src/components/landingPageComp/GetInTouch.jsx, src/pages/property/Listing.jsx
1. The same request from the homepage to the listing.
2. Remove the area and locality from the URL by clicking on the (x) icon.
3. The locality should not be removed when the area is removed.
4. The dependency of the area on the locality has been modified.
=> Map Height

src/pages/Dashboard/landlord/LandlordDashboardMyFavourites.jsx
Favorite page in admin dashboard
Updated the UI as per figma
Added functionality to view all button
=> View all button feature added UI updated

src/components/AboutComp/About_Card.jsx, src/components/navbar/NavBar.jsx, src/pages/Login/Login.jsx, src/pages/property/listingComponents/Cards.jsx, src/pages/property/listingComponents/Toggle.jsx
Toggle availability frontend and about us
=> Toggle availability frontend and about us

src/components/AboutComp/About_Card.jsx, src/pages/About/about.css
About 1440px responsiveness after pulling changes
=> About 1440px responsiveness

package-lock.json, src/pages/Dashboard/landlord/LandlordDashboardWelcomePage.jsx, src/pages/property/Listing.jsx, src/pages/property/listingComponents/Cards.jsx, src/pages/property/listingComponents/Toggle.jsx
frontend commit toggle, sort, about us, dashboard
=> frontend commit toggle, sort, about us, dashboard

src/pages/About/about.css, src/pages/Dashboard/landlord/LandlordDashboardAccountSecurity.jsx, src/pages/Dashboard/landlord/LandlordDashboardMyFavourites.jsx, src/pages/Dashboard/landlord/LandlordDashboardMyProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardProfileForm.jsx, src/pages/Dashboard/landlord/LandlordDashboardWelcomePage.jsx
Tayiab, omkar and paras made changes to dashboard along with respinsivens
=> dashord changes made

package-lock.json, src/pages/Dashboard/landlord/LandlordDashboardAddProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardSidebar.jsx, src/pages/property/listingComponents/Cards.jsx
sidebar gap added, add property timeline updated, cards share button added
=> minor changes made

src/pages/Dashboard/landlord/LandlordDashboardMyFavourites.jsx, src/pages/Dashboard/landlord/LandlordDashboardMyProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardWelcomePage.jsx
- Removed sort options on Favourite page
- Aligned the pop-up text at the center of Favourite icon
=> Removed Sort options on Dashboard's Favourite page

src/pages/Pricing/Pricing.jsx
=> Changes in Pricing Component

src/pages/Pricing/Pricing.jsx
=> Minor Changes

src/pages/Dashboard/landlord/LandlordDashboardMyFavourites.jsx, src/pages/Dashboard/landlord/LandlordDashboardMyProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardWelcomePage.jsx, src/pages/PropertyListing/CompareProperties/CompareProperty.jsx, src/pages/PropertyListing/Listings/components/Cards.jsx, src/pages/PropertyListing/ViewProperty/PropertyBrief.jsx, src/pages/PropertyListing/ViewProperty/components/Reviews.jsx, src/pages/property/compare-prop/CompareProperty.jsx
- Share icon popup position changed to bottom right
- Now we can view the "Write a Review" form on mobile
=> Update regardin Share icon Popup & Write a review form

src/pages/PropertyListing/CompareProperties/CompareProperty.jsx
Favourite icon is now functional; updated in CompareProperty.jsx
=> Favourite icon is now functional; updated in CompareProperty.jsx

src/pages/PropertyListing/CompareProperties/CompareProperty.jsx
Fixed the Favourite icon's function
=>  Fixed the Favourite icon's function

package-lock.json, src/pages/PropertyListing/Listings/Listings.jsx, src/pages/PropertyListing/ViewProperty/PropertyBrief.jsx, src/pages/PropertyListing/ViewProperty/PropertyDetails.jsx, src/pages/PropertyListing/ViewProperty/components/Location.jsx, src/pages/PropertyListing/ViewProperty/components/NewReviews.jsx
- Added NewReview.jsx
- Fixed the Fav icon in the Property details page
- Updated Location.jsx:  made it map & get direction text clickable
- Listing.jsx Visit Button: added sm:px-7 to make text center
=> Few updates

package-lock.json, src/config/constant.js, src/constant_pricing/Subscriptions/index.js, src/constant_pricing/index.js, src/pages/Dashboard/landlord/AllForms/NewForm.jsx, src/pages/Dashboard/landlord/AllForms/PricngCard.jsx, src/pages/Dashboard/landlord/LandlordDashboardAddProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardEditProperties.jsx, src/pages/PropertyListing/Listings/Listings.jsx, src/pages/PropertyListing/ViewProperty/components/Location.jsx
Added New Add Property Form as per Figma
=> Added New Add Property Form as per Figma

src/pages/Dashboard/landlord/AllForms/NewForm.jsx
Added google map to New Add Property Form
=> Added google map to New Add Property Form

src/pages/PropertyListing/ViewProperty/components/Regulations.jsx
Removed Pets Allowed in Regulations
- As per the new Add property form, their  is new input regarding pets allowed
=> Removed Pets Allowed in Regulations

src/pages/PropertyListing/ViewProperty/components/NewReviews.jsx, src/pages/PropertyListing/ViewProperty/components/Reviews.jsx
update review components all users fetch correct more accurate star
=> update review components

src/pages/Blog/Blog.jsx, src/pages/Blog/components/BlogBody.jsx
- On hover on Blog Card's Title, gets underlined
- Updated Tending Blogs as Default
=> Blog Page 2 Changes or Updates

src/config/constant.js, src/pages/Blog/components/BlogBody.jsx, src/pages/Blog/components/BlogItem.jsx, src/pages/PropertyListing/ViewProperty/components/Location.jsx, src/pages/blog/Blog.jsx
Blogs 3 changes
- Blog's Default is Treending
- On hover on Blog, the Blog Title gets underlined
- Pagination is removed & added loading
=> Blog page 3 changes & Location address is masked

src/pages/PropertyListing/Listings/Listings.jsx, src/pages/PropertyListing/Listings/components/LoginPopup/LoginPopup.css, src/pages/PropertyListing/Listings/components/LoginPopup/LoginPopup.jsx, src/reusableComponents/Navbar.jsx
- Login Popup on click on "Visit" Button on Property Listing page
- Added "Add Property" to Navbar
=> Login Popup on click on Visit Button & added Add Property to Navabar

src/config/constant.js, src/pages/Blog/Blog.jsx, src/pages/Dashboard/landlord/LandlordDashboardSidebar.jsx, src/pages/PropertyListing/Listings/Listings.jsx, src/reusableComponents/Navbar.jsx
Changes Done:
- Added "Load more" button on 
- Blog page
- Property Listing page
- Alignment Dashboard on dashboard side bar fixed
- On hover, the navbar's option background color changes as per Figma. 
- Without Login, on Navbar, Login/Sign up, it is button design changed as per Figma
=> Added Load More button on Blogs & Property Listing page

src/pages/Home/components/PropertyCarousel.jsx, src/pages/Login/Login.css, src/pages/Login/Login.jsx, src/pages/Register/Register.css, src/pages/Register/Register.jsx
- fix the extra space on bottom in register page
- refactor login page
- removed unnecessary custom css in login.css
- fix the slider component in property carousel component
=> UI changes in login and register and slider component

src/pages/Dashboard/landlord/AllForms/NewForm.jsx, src/pages/Home/components/HiringPartners.jsx
Add Property Form - Grid view of images fixed as per figma
=> Add Property Form - Grid view of images fixed as per figma

src/pages/Dashboard/landlord/LandlordDashboardAddProperties.jsx, src/pages/Dashboard/landlord/NewForm/PricngCard.jsx, src/pages/Dashboard/landlord/NewForm/SupportModal.jsx, src/pages/Dashboard/landlord/NewForm/components/AdditionalInfo.jsx, src/pages/Dashboard/landlord/NewForm/components/Coupon.jsx, src/pages/Dashboard/landlord/NewForm/components/Details.jsx, src/pages/Dashboard/landlord/NewForm/components/ImageUpload.jsx, src/pages/Dashboard/landlord/NewForm/components/SubscriptionCards.jsx, src/reusableComponents/Navbar.jsx
- New Add Property Form assembled according to Figma.
- Added Background to "+Add New Property" on Navbar, according to Figma
=> New Add Property Form assembled according to Figma.

src/config/constant.js, src/pages/PropertyListing/ViewProperty/PropertyBrief.jsx
removed red bg while dragging button
=> remove red bg 

src/pages/Dashboard/landlord/AllForms/NewForm.jsx, src/pages/Dashboard/landlord/LandlordDashboardAddProperties.jsx, src/pages/Dashboard/landlord/LandlordDashboardEditProperties.jsx, src/pages/Dashboard/landlord/NewForm/components/AdditionalInfo.jsx, src/pages/Dashboard/landlord/NewForm/components/Coupon.jsx, src/pages/Dashboard/landlord/NewForm/components/Details.jsx, src/pages/Dashboard/landlord/NewForm/components/ImageUpload.jsx
change the edit property page to use new forms
=> Edit property page

src/pages/Dashboard/landlord/LandlordDashboardWelcomePage.jsx, src/pages/Dashboard/landlord/NewForm/components/AdditionalInfo.jsx, src/pages/Dashboard/landlord/NewForm/components/Details.jsx
Made the dropdown ui according to figma designs
=> Dropdown ui

src/pages/Dashboard/landlord/LandlordDashboardSidebar.jsx
fix the sidebar redirect issue on clicking settings
=> fix the sidebar redirect issue

src/pages/Dashboard/landlord/NewForm/PricngCard.jsx, src/pages/Dashboard/landlord/NewForm/components/AdditionalInfo.jsx, src/pages/Dashboard/landlord/NewForm/components/Details.jsx
fix subscription cards ui and move the heading to center in mobiles
=> fix subscription cards ui

src/pages/PropertyListing/Listings/Listings.jsx
Fix double click issue in listings page
=> Fix double click issue in listings page

src/pages/About/components/Faq.jsx, src/pages/Contact/Contact.jsx
Update from Shivank, Contact form and faq UI updated
=> Required UI updated

src/pages/Dashboard/landlord/NewForm/components/AdditionalInfo.jsx, src/pages/Dashboard/landlord/NewForm/components/Details.jsx, src/pages/Register/Register.jsx
Password verfication added to the registeration form and required changes done in add property form
=> Changes done in add property page and register page

src/pages/Register/Register.jsx
=> Commented Out Google OAuth

src/pages/Login/Login.jsx
=> Cpmmented out OAuth from Login
